packages:
  # all packages in subdirs of docs/
  - 'docs'
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # exclude packages that are inside test directories
  - 'packages/**/__tests__/**'
