packages:
    # include packages that are inside this directories
    - 'docs'
    - 'packages/*'

    # exclude packages that are inside this directories
    - '!packages/create-arvis'
    - '!packages/**/__tests__/**'
