name: Playwright Tests

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  deployment_status:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node_version: [20]

    if: github.event.deployment_status.state == 'success'

    # @see https://pnpm.io/continuous-integration#github-actions
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - run: pnpm install
      - run: pnpm test:e2e
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.node_version }}-${{ github.run_id }}
          path: playwright-report/
          retention-days: 30
