name: Rel

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install pnpm
              run: npm install -g pnpm@9.1.1

            - name: Install dependencies
              run: pnpm install

            - name: Run release
              run: pnpm run mono
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
